// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mobiliva.DataAccess.Data;

#nullable disable

namespace Mobiliva.DataAccess.Migrations
{
    [DbContext(typeof(MobilivaDbContext))]
    [Migration("20220725091814_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mobiliva.DataAccess.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerGSM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Mobiliva.DataAccess.Data.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Mobiliva.DataAccess.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Unit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 410030369,
                            Category = "Jewelery",
                            CreatedBy = "Cynthia",
                            CreatedDate = new DateTime(2021, 11, 11, 21, 21, 55, 195, DateTimeKind.Local).AddTicks(6086),
                            Description = "Qui sint omnis est expedita. Ut et velit iure rerum rerum qui laudantium itaque. Inventore qui fugit assumenda ea molestiae. Ipsam placeat ipsum cum.",
                            Status = "Crest",
                            Unit = 29m,
                            UnitPrice = 20204m,
                            UpdatedBy = "Cynthia",
                            UpdatedDate = new DateTime(2021, 12, 20, 4, 38, 28, 287, DateTimeKind.Local).AddTicks(2221)
                        },
                        new
                        {
                            Id = 569920344,
                            Category = "Movies",
                            CreatedBy = "Terence",
                            CreatedDate = new DateTime(2022, 2, 25, 0, 12, 25, 192, DateTimeKind.Local).AddTicks(8289),
                            Description = "Cumque a eveniet voluptatem dolorum inventore sequi quis excepturi. Perspiciatis a voluptas omnis ut.",
                            Status = "next-generation",
                            Unit = 869m,
                            UnitPrice = 48677m,
                            UpdatedBy = "Terence",
                            UpdatedDate = new DateTime(2022, 3, 18, 20, 15, 49, 126, DateTimeKind.Local).AddTicks(1219)
                        },
                        new
                        {
                            Id = 726397805,
                            Category = "Games",
                            CreatedBy = "Eloise",
                            CreatedDate = new DateTime(2022, 6, 11, 2, 2, 4, 294, DateTimeKind.Local).AddTicks(5644),
                            Description = "Ab corrupti quia aut eveniet et quidem. Non et nihil nostrum. Voluptatem consequuntur nisi beatae eum nemo excepturi dignissimos enim animi.",
                            Status = "Assurance",
                            Unit = 193m,
                            UnitPrice = 19837m,
                            UpdatedBy = "Eloise",
                            UpdatedDate = new DateTime(2021, 10, 13, 9, 46, 28, 938, DateTimeKind.Local).AddTicks(4272)
                        },
                        new
                        {
                            Id = 270765875,
                            Category = "Industrial",
                            CreatedBy = "Jesse",
                            CreatedDate = new DateTime(2022, 7, 4, 4, 51, 16, 948, DateTimeKind.Local).AddTicks(3490),
                            Description = "Voluptatem aut voluptatem atque hic possimus nihil magnam sed voluptas. Necessitatibus rem est rerum veritatis ea tempore commodi distinctio. Aut necessitatibus alias autem.",
                            Status = "local area network",
                            Unit = 988m,
                            UnitPrice = 12946m,
                            UpdatedBy = "Jesse",
                            UpdatedDate = new DateTime(2021, 10, 30, 17, 44, 43, 198, DateTimeKind.Local).AddTicks(9685)
                        },
                        new
                        {
                            Id = 381010334,
                            Category = "Health",
                            CreatedBy = "Karl",
                            CreatedDate = new DateTime(2022, 4, 12, 13, 0, 21, 946, DateTimeKind.Local).AddTicks(9414),
                            Description = "Facilis et sit accusantium amet id. Et quo asperiores dolorum excepturi.",
                            Status = "Afghani",
                            Unit = 610m,
                            UnitPrice = 1194m,
                            UpdatedBy = "Karl",
                            UpdatedDate = new DateTime(2021, 12, 26, 13, 23, 51, 930, DateTimeKind.Local).AddTicks(8597)
                        },
                        new
                        {
                            Id = 318364140,
                            Category = "Automotive",
                            CreatedBy = "Kelvin",
                            CreatedDate = new DateTime(2021, 11, 5, 2, 0, 1, 751, DateTimeKind.Local).AddTicks(1226),
                            Description = "A ipsam a quia aut deleniti quod error nemo in. Ea velit doloremque unde. Aliquam mollitia sit aut quis vel aut sequi.",
                            Status = "user-facing",
                            Unit = 388m,
                            UnitPrice = 21093m,
                            UpdatedBy = "Kelvin",
                            UpdatedDate = new DateTime(2021, 9, 4, 23, 18, 33, 972, DateTimeKind.Local).AddTicks(8922)
                        },
                        new
                        {
                            Id = 225841831,
                            Category = "Movies",
                            CreatedBy = "Harvey",
                            CreatedDate = new DateTime(2022, 5, 1, 11, 1, 14, 405, DateTimeKind.Local).AddTicks(50),
                            Description = "Minima deleniti molestiae dolor provident cum minima nobis. Natus quia eos facilis harum eos aperiam.",
                            Status = "microchip",
                            Unit = 211m,
                            UnitPrice = 38652m,
                            UpdatedBy = "Harvey",
                            UpdatedDate = new DateTime(2022, 6, 30, 4, 12, 22, 532, DateTimeKind.Local).AddTicks(4302)
                        },
                        new
                        {
                            Id = 169057772,
                            Category = "Jewelery",
                            CreatedBy = "Louise",
                            CreatedDate = new DateTime(2021, 10, 14, 2, 54, 2, 141, DateTimeKind.Local).AddTicks(7027),
                            Description = "Repellendus iusto sequi omnis. Unde qui eligendi necessitatibus quia ut aut non doloribus.",
                            Status = "SDD",
                            Unit = 116m,
                            UnitPrice = 2727m,
                            UpdatedBy = "Louise",
                            UpdatedDate = new DateTime(2021, 8, 21, 15, 41, 24, 231, DateTimeKind.Local).AddTicks(9447)
                        },
                        new
                        {
                            Id = 478357395,
                            Category = "Tools",
                            CreatedBy = "Roosevelt",
                            CreatedDate = new DateTime(2021, 12, 28, 20, 49, 45, 466, DateTimeKind.Local).AddTicks(6918),
                            Description = "Dolores qui ut in.",
                            Status = "reboot",
                            Unit = 824m,
                            UnitPrice = 23083m,
                            UpdatedBy = "Roosevelt",
                            UpdatedDate = new DateTime(2021, 10, 2, 17, 46, 17, 973, DateTimeKind.Local).AddTicks(1801)
                        },
                        new
                        {
                            Id = 862023818,
                            Category = "Beauty",
                            CreatedBy = "Francis",
                            CreatedDate = new DateTime(2021, 12, 11, 7, 45, 9, 376, DateTimeKind.Local).AddTicks(3447),
                            Description = "Unde explicabo aut ab iste itaque sit iure quis et. Voluptas ea a esse sed debitis.",
                            Status = "Savings Account",
                            Unit = 826m,
                            UnitPrice = 35039m,
                            UpdatedBy = "Francis",
                            UpdatedDate = new DateTime(2021, 11, 25, 0, 20, 52, 807, DateTimeKind.Local).AddTicks(6301)
                        },
                        new
                        {
                            Id = 640443182,
                            Category = "Industrial",
                            CreatedBy = "Winston",
                            CreatedDate = new DateTime(2022, 7, 4, 8, 33, 10, 783, DateTimeKind.Local).AddTicks(4166),
                            Description = "Qui dolores qui. Cumque dolores placeat accusamus. Autem dolores fugiat illum.",
                            Status = "Fresh",
                            Unit = 386m,
                            UnitPrice = 42074m,
                            UpdatedBy = "Winston",
                            UpdatedDate = new DateTime(2021, 12, 19, 15, 7, 52, 892, DateTimeKind.Local).AddTicks(4763)
                        },
                        new
                        {
                            Id = 514454634,
                            Category = "Tools",
                            CreatedBy = "Jacob",
                            CreatedDate = new DateTime(2022, 2, 20, 9, 20, 30, 406, DateTimeKind.Local).AddTicks(9416),
                            Description = "Odio dolorum officiis consequuntur. Aut non ipsam et officia enim voluptate qui occaecati velit.",
                            Status = "disintermediate",
                            Unit = 181m,
                            UnitPrice = 16298m,
                            UpdatedBy = "Jacob",
                            UpdatedDate = new DateTime(2022, 6, 29, 1, 43, 34, 343, DateTimeKind.Local).AddTicks(4284)
                        },
                        new
                        {
                            Id = 310931031,
                            Category = "Health",
                            CreatedBy = "Julie",
                            CreatedDate = new DateTime(2021, 8, 6, 15, 8, 47, 639, DateTimeKind.Local).AddTicks(8657),
                            Description = "Aliquam voluptatem iste accusamus beatae sint sed id. Corporis ut exercitationem repudiandae.",
                            Status = "purple",
                            Unit = 585m,
                            UnitPrice = 2486m,
                            UpdatedBy = "Julie",
                            UpdatedDate = new DateTime(2022, 3, 17, 21, 14, 7, 404, DateTimeKind.Local).AddTicks(152)
                        },
                        new
                        {
                            Id = 732627090,
                            Category = "Music",
                            CreatedBy = "Rebecca",
                            CreatedDate = new DateTime(2022, 4, 8, 16, 42, 52, 50, DateTimeKind.Local).AddTicks(6867),
                            Description = "Excepturi in explicabo reiciendis est minima illum unde temporibus. Alias placeat possimus aut est est recusandae quod ab ipsam. Molestiae eum eveniet eligendi nobis. Dolores quia voluptatum itaque.",
                            Status = "efficient",
                            Unit = 350m,
                            UnitPrice = 42227m,
                            UpdatedBy = "Rebecca",
                            UpdatedDate = new DateTime(2021, 12, 15, 11, 6, 15, 305, DateTimeKind.Local).AddTicks(8929)
                        },
                        new
                        {
                            Id = 621062628,
                            Category = "Jewelery",
                            CreatedBy = "Margie",
                            CreatedDate = new DateTime(2021, 12, 26, 20, 2, 23, 940, DateTimeKind.Local).AddTicks(5616),
                            Description = "Est nostrum qui molestias omnis sit sunt id fugit nisi. Veniam sequi in. Ut voluptatem expedita sed accusamus necessitatibus et eveniet qui temporibus. Quo quis rerum qui cupiditate omnis odio voluptatem sed.",
                            Status = "payment",
                            Unit = 354m,
                            UnitPrice = 38158m,
                            UpdatedBy = "Margie",
                            UpdatedDate = new DateTime(2021, 7, 28, 13, 8, 13, 573, DateTimeKind.Local).AddTicks(5114)
                        },
                        new
                        {
                            Id = 337323229,
                            Category = "Tools",
                            CreatedBy = "Jimmy",
                            CreatedDate = new DateTime(2022, 1, 28, 15, 49, 42, 265, DateTimeKind.Local).AddTicks(9876),
                            Description = "Voluptatem repellendus earum.",
                            Status = "bricks-and-clicks",
                            Unit = 745m,
                            UnitPrice = 37051m,
                            UpdatedBy = "Jimmy",
                            UpdatedDate = new DateTime(2022, 4, 15, 7, 2, 0, 189, DateTimeKind.Local).AddTicks(2880)
                        },
                        new
                        {
                            Id = 376958253,
                            Category = "Beauty",
                            CreatedBy = "Olivia",
                            CreatedDate = new DateTime(2021, 8, 13, 16, 24, 3, 922, DateTimeKind.Local).AddTicks(6682),
                            Description = "Necessitatibus dolorem odio repellendus veniam perspiciatis ea. Beatae aut cumque beatae sit temporibus consectetur. Quaerat odio quae aliquam reprehenderit dolor voluptas consequatur quia tempora.",
                            Status = "adapter",
                            Unit = 238m,
                            UnitPrice = 35155m,
                            UpdatedBy = "Olivia",
                            UpdatedDate = new DateTime(2022, 5, 27, 14, 59, 42, 831, DateTimeKind.Local).AddTicks(1990)
                        },
                        new
                        {
                            Id = 656203612,
                            Category = "Jewelery",
                            CreatedBy = "Florence",
                            CreatedDate = new DateTime(2022, 7, 22, 1, 49, 11, 483, DateTimeKind.Local).AddTicks(630),
                            Description = "Provident voluptas nesciunt accusantium molestiae enim nulla. Aut mollitia veniam.",
                            Status = "Ergonomic Wooden Chips",
                            Unit = 381m,
                            UnitPrice = 43161m,
                            UpdatedBy = "Florence",
                            UpdatedDate = new DateTime(2022, 5, 11, 0, 5, 32, 135, DateTimeKind.Local).AddTicks(1139)
                        },
                        new
                        {
                            Id = 120694813,
                            Category = "Books",
                            CreatedBy = "Janis",
                            CreatedDate = new DateTime(2022, 2, 6, 8, 13, 50, 415, DateTimeKind.Local).AddTicks(6991),
                            Description = "Omnis nostrum accusamus totam aliquid tempore. Temporibus quia nemo fuga sequi quam.",
                            Status = "microchip",
                            Unit = 282m,
                            UnitPrice = 10337m,
                            UpdatedBy = "Janis",
                            UpdatedDate = new DateTime(2021, 9, 4, 4, 42, 54, 430, DateTimeKind.Local).AddTicks(197)
                        },
                        new
                        {
                            Id = 113309625,
                            Category = "Shoes",
                            CreatedBy = "Daisy",
                            CreatedDate = new DateTime(2021, 10, 8, 3, 56, 5, 73, DateTimeKind.Local).AddTicks(7705),
                            Description = "Esse natus quae consequatur eos aut dolorem ut minima nihil. Illum est dolor commodi vitae ipsum impedit repudiandae facere ullam. Perspiciatis voluptatibus vel facilis explicabo quis necessitatibus.",
                            Status = "Tools & Beauty",
                            Unit = 267m,
                            UnitPrice = 38649m,
                            UpdatedBy = "Daisy",
                            UpdatedDate = new DateTime(2021, 10, 20, 18, 39, 0, 942, DateTimeKind.Local).AddTicks(6988)
                        },
                        new
                        {
                            Id = 388594755,
                            Category = "Automotive",
                            CreatedBy = "Arnold",
                            CreatedDate = new DateTime(2022, 7, 6, 19, 52, 12, 49, DateTimeKind.Local).AddTicks(256),
                            Description = "Beatae id qui quas iste consequuntur. Corporis minus pariatur ipsa quia necessitatibus.",
                            Status = "Marketing",
                            Unit = 308m,
                            UnitPrice = 3296m,
                            UpdatedBy = "Arnold",
                            UpdatedDate = new DateTime(2022, 5, 13, 1, 47, 31, 294, DateTimeKind.Local).AddTicks(142)
                        },
                        new
                        {
                            Id = 756253178,
                            Category = "Beauty",
                            CreatedBy = "Irving",
                            CreatedDate = new DateTime(2022, 6, 22, 13, 53, 12, 860, DateTimeKind.Local).AddTicks(1879),
                            Description = "Ex quis harum sed exercitationem quos ab. Dolor atque labore facilis tempore ipsam aut consequatur. Aut quos sit.",
                            Status = "Venezuela",
                            Unit = 772m,
                            UnitPrice = 38486m,
                            UpdatedBy = "Irving",
                            UpdatedDate = new DateTime(2022, 6, 15, 19, 23, 12, 730, DateTimeKind.Local).AddTicks(3547)
                        },
                        new
                        {
                            Id = 395147740,
                            Category = "Electronics",
                            CreatedBy = "Vernon",
                            CreatedDate = new DateTime(2021, 10, 29, 19, 51, 3, 883, DateTimeKind.Local).AddTicks(4591),
                            Description = "Culpa itaque placeat voluptatum earum quaerat minus earum voluptatem. Nostrum quia et natus similique. Eveniet eaque qui ipsum blanditiis iure dolores suscipit dolores.",
                            Status = "Jamaican Dollar",
                            Unit = 889m,
                            UnitPrice = 24988m,
                            UpdatedBy = "Vernon",
                            UpdatedDate = new DateTime(2022, 1, 27, 7, 38, 32, 628, DateTimeKind.Local).AddTicks(2873)
                        },
                        new
                        {
                            Id = 234595683,
                            Category = "Industrial",
                            CreatedBy = "Wm",
                            CreatedDate = new DateTime(2022, 2, 22, 3, 27, 24, 1, DateTimeKind.Local).AddTicks(1100),
                            Description = "Illo consequatur sunt laborum. Vel maxime optio quia voluptatem asperiores. Totam consequatur quis.",
                            Status = "Rustic Frozen Salad",
                            Unit = 373m,
                            UnitPrice = 24m,
                            UpdatedBy = "Wm",
                            UpdatedDate = new DateTime(2022, 4, 6, 6, 7, 18, 599, DateTimeKind.Local).AddTicks(8206)
                        },
                        new
                        {
                            Id = 844317218,
                            Category = "Jewelery",
                            CreatedBy = "Erma",
                            CreatedDate = new DateTime(2022, 4, 29, 7, 27, 35, 431, DateTimeKind.Local).AddTicks(2569),
                            Description = "Consequatur iure ipsam occaecati qui est.",
                            Status = "Engineer",
                            Unit = 960m,
                            UnitPrice = 20664m,
                            UpdatedBy = "Erma",
                            UpdatedDate = new DateTime(2021, 8, 18, 12, 26, 44, 414, DateTimeKind.Local).AddTicks(2292)
                        },
                        new
                        {
                            Id = 571782413,
                            Category = "Movies",
                            CreatedBy = "Geneva",
                            CreatedDate = new DateTime(2022, 4, 26, 19, 3, 23, 365, DateTimeKind.Local).AddTicks(5321),
                            Description = "Reprehenderit in quis sit quod ea sit nulla ad. Autem sit omnis id dolor et id.",
                            Status = "Knolls",
                            Unit = 427m,
                            UnitPrice = 15346m,
                            UpdatedBy = "Geneva",
                            UpdatedDate = new DateTime(2021, 12, 7, 22, 53, 44, 80, DateTimeKind.Local).AddTicks(1503)
                        },
                        new
                        {
                            Id = 650806235,
                            Category = "Sports",
                            CreatedBy = "Lula",
                            CreatedDate = new DateTime(2021, 8, 3, 5, 36, 40, 832, DateTimeKind.Local).AddTicks(1691),
                            Description = "Nulla ullam eveniet vitae qui itaque quisquam eveniet. Aperiam quia ea ullam enim laboriosam et consequuntur natus. Tenetur fugit omnis. Earum qui distinctio harum quibusdam perferendis quae accusamus sit.",
                            Status = "Manager",
                            Unit = 132m,
                            UnitPrice = 37751m,
                            UpdatedBy = "Lula",
                            UpdatedDate = new DateTime(2022, 3, 25, 19, 47, 19, 407, DateTimeKind.Local).AddTicks(1095)
                        },
                        new
                        {
                            Id = 707148390,
                            Category = "Electronics",
                            CreatedBy = "Pearl",
                            CreatedDate = new DateTime(2021, 8, 14, 20, 25, 26, 802, DateTimeKind.Local).AddTicks(8095),
                            Description = "Placeat dolores rerum voluptatem consequatur esse ut est. Hic optio perferendis voluptatem quia iusto eligendi temporibus voluptatem est. Voluptatem repellendus voluptate. Quaerat ut praesentium.",
                            Status = "Berkshire",
                            Unit = 312m,
                            UnitPrice = 36187m,
                            UpdatedBy = "Pearl",
                            UpdatedDate = new DateTime(2022, 2, 26, 7, 23, 4, 915, DateTimeKind.Local).AddTicks(253)
                        },
                        new
                        {
                            Id = 388856154,
                            Category = "Games",
                            CreatedBy = "Cesar",
                            CreatedDate = new DateTime(2022, 4, 1, 7, 8, 54, 452, DateTimeKind.Local).AddTicks(2471),
                            Description = "Autem quisquam aut sint et velit amet autem adipisci qui. Placeat sunt deserunt qui veniam vel.",
                            Status = "withdrawal",
                            Unit = 449m,
                            UnitPrice = 14870m,
                            UpdatedBy = "Cesar",
                            UpdatedDate = new DateTime(2022, 6, 18, 8, 7, 18, 767, DateTimeKind.Local).AddTicks(4992)
                        },
                        new
                        {
                            Id = 842461372,
                            Category = "Music",
                            CreatedBy = "Edward",
                            CreatedDate = new DateTime(2022, 3, 2, 10, 37, 48, 489, DateTimeKind.Local).AddTicks(515),
                            Description = "Dolorem dicta cum voluptatem cum impedit odio ipsa.",
                            Status = "cross-platform",
                            Unit = 445m,
                            UnitPrice = 38838m,
                            UpdatedBy = "Edward",
                            UpdatedDate = new DateTime(2022, 1, 4, 12, 56, 48, 748, DateTimeKind.Local).AddTicks(3659)
                        },
                        new
                        {
                            Id = 559334795,
                            Category = "Toys",
                            CreatedBy = "Kenny",
                            CreatedDate = new DateTime(2021, 8, 5, 7, 31, 3, 907, DateTimeKind.Local).AddTicks(5678),
                            Description = "Dolorum cum sed adipisci laudantium aut aperiam.",
                            Status = "Spring",
                            Unit = 2m,
                            UnitPrice = 33802m,
                            UpdatedBy = "Kenny",
                            UpdatedDate = new DateTime(2022, 5, 29, 0, 25, 21, 334, DateTimeKind.Local).AddTicks(6064)
                        },
                        new
                        {
                            Id = 696993844,
                            Category = "Music",
                            CreatedBy = "Stephen",
                            CreatedDate = new DateTime(2022, 7, 2, 15, 25, 10, 788, DateTimeKind.Local).AddTicks(2307),
                            Description = "Et quaerat reprehenderit explicabo ullam debitis architecto inventore quia totam.",
                            Status = "Guyana Dollar",
                            Unit = 970m,
                            UnitPrice = 6205m,
                            UpdatedBy = "Stephen",
                            UpdatedDate = new DateTime(2022, 4, 18, 7, 13, 9, 250, DateTimeKind.Local).AddTicks(441)
                        },
                        new
                        {
                            Id = 754507475,
                            Category = "Health",
                            CreatedBy = "Jessie",
                            CreatedDate = new DateTime(2022, 6, 9, 13, 56, 37, 22, DateTimeKind.Local).AddTicks(3343),
                            Description = "Corrupti id labore dolores fuga est error. Labore fugit facilis labore eveniet ipsam.",
                            Status = "collaborative",
                            Unit = 988m,
                            UnitPrice = 6728m,
                            UpdatedBy = "Jessie",
                            UpdatedDate = new DateTime(2022, 5, 25, 11, 54, 20, 2, DateTimeKind.Local).AddTicks(3633)
                        },
                        new
                        {
                            Id = 187131789,
                            Category = "Movies",
                            CreatedBy = "Jaime",
                            CreatedDate = new DateTime(2022, 4, 22, 2, 39, 37, 927, DateTimeKind.Local).AddTicks(614),
                            Description = "Voluptas accusantium unde debitis quas voluptate praesentium consequatur asperiores. Aliquam eveniet sed provident alias quibusdam laboriosam. Aut maiores dolorum qui perspiciatis rem nihil nobis autem sint.",
                            Status = "database",
                            Unit = 457m,
                            UnitPrice = 10902m,
                            UpdatedBy = "Jaime",
                            UpdatedDate = new DateTime(2022, 5, 8, 8, 33, 52, 155, DateTimeKind.Local).AddTicks(2447)
                        },
                        new
                        {
                            Id = 667300881,
                            Category = "Toys",
                            CreatedBy = "Charles",
                            CreatedDate = new DateTime(2022, 2, 26, 6, 8, 16, 924, DateTimeKind.Local).AddTicks(2887),
                            Description = "Omnis voluptates omnis nobis voluptate. Non voluptatem officiis iure deserunt sint nihil. Nam sit doloribus magnam necessitatibus ea provident doloremque. Quibusdam et vero rerum cumque repudiandae.",
                            Status = "end-to-end",
                            Unit = 641m,
                            UnitPrice = 9913m,
                            UpdatedBy = "Charles",
                            UpdatedDate = new DateTime(2022, 6, 20, 4, 45, 29, 410, DateTimeKind.Local).AddTicks(8476)
                        },
                        new
                        {
                            Id = 560732192,
                            Category = "Games",
                            CreatedBy = "Jeffery",
                            CreatedDate = new DateTime(2022, 7, 13, 15, 37, 49, 422, DateTimeKind.Local).AddTicks(9615),
                            Description = "Eaque porro sit tenetur et quas delectus eligendi reprehenderit labore. Illum illo eos cum perferendis. Quaerat harum quam sint. Excepturi iure laborum impedit dolores.",
                            Status = "Intelligent",
                            Unit = 425m,
                            UnitPrice = 2888m,
                            UpdatedBy = "Jeffery",
                            UpdatedDate = new DateTime(2021, 11, 17, 22, 9, 7, 935, DateTimeKind.Local).AddTicks(5435)
                        },
                        new
                        {
                            Id = 842157751,
                            Category = "Games",
                            CreatedBy = "Edmond",
                            CreatedDate = new DateTime(2021, 10, 19, 12, 32, 7, 232, DateTimeKind.Local).AddTicks(3383),
                            Description = "Saepe aut dolor ut voluptate. Et assumenda fugit omnis eius.",
                            Status = "Bedfordshire",
                            Unit = 549m,
                            UnitPrice = 45487m,
                            UpdatedBy = "Edmond",
                            UpdatedDate = new DateTime(2022, 4, 23, 10, 25, 43, 707, DateTimeKind.Local).AddTicks(6314)
                        },
                        new
                        {
                            Id = 765395644,
                            Category = "Computers",
                            CreatedBy = "Van",
                            CreatedDate = new DateTime(2021, 10, 20, 3, 10, 47, 51, DateTimeKind.Local).AddTicks(2525),
                            Description = "Illo delectus aut molestias provident. Ad fugiat veniam iure eos ratione reiciendis. Suscipit eaque sint nam quisquam in aut repellat.",
                            Status = "Soft",
                            Unit = 367m,
                            UnitPrice = 16465m,
                            UpdatedBy = "Van",
                            UpdatedDate = new DateTime(2021, 11, 10, 8, 36, 50, 988, DateTimeKind.Local).AddTicks(5065)
                        },
                        new
                        {
                            Id = 704899335,
                            Category = "Outdoors",
                            CreatedBy = "Tammy",
                            CreatedDate = new DateTime(2021, 11, 22, 21, 1, 30, 344, DateTimeKind.Local).AddTicks(311),
                            Description = "Quos voluptatem error in dolores reprehenderit ratione incidunt nisi. Nulla asperiores earum tenetur blanditiis.",
                            Status = "Liberia",
                            Unit = 293m,
                            UnitPrice = 1106m,
                            UpdatedBy = "Tammy",
                            UpdatedDate = new DateTime(2022, 3, 11, 21, 11, 10, 112, DateTimeKind.Local).AddTicks(8364)
                        },
                        new
                        {
                            Id = 505556037,
                            Category = "Games",
                            CreatedBy = "Jared",
                            CreatedDate = new DateTime(2021, 8, 31, 0, 5, 36, 379, DateTimeKind.Local).AddTicks(3830),
                            Description = "Repellat hic optio ea. Non ut incidunt explicabo voluptatibus a magni qui.",
                            Status = "Minnesota",
                            Unit = 573m,
                            UnitPrice = 33534m,
                            UpdatedBy = "Jared",
                            UpdatedDate = new DateTime(2022, 5, 17, 14, 17, 14, 740, DateTimeKind.Local).AddTicks(6429)
                        },
                        new
                        {
                            Id = 710730218,
                            Category = "Games",
                            CreatedBy = "Myrtle",
                            CreatedDate = new DateTime(2021, 10, 29, 21, 38, 38, 940, DateTimeKind.Local).AddTicks(3577),
                            Description = "Nulla ab nostrum architecto eos quo quia. Consectetur sunt accusantium sit praesentium suscipit cum. Optio placeat est dolor. Error beatae molestiae praesentium.",
                            Status = "Fantastic Granite Pizza",
                            Unit = 158m,
                            UnitPrice = 12050m,
                            UpdatedBy = "Myrtle",
                            UpdatedDate = new DateTime(2021, 9, 10, 16, 46, 51, 624, DateTimeKind.Local).AddTicks(8795)
                        },
                        new
                        {
                            Id = 447936620,
                            Category = "Electronics",
                            CreatedBy = "Jake",
                            CreatedDate = new DateTime(2022, 6, 8, 5, 9, 41, 654, DateTimeKind.Local).AddTicks(1061),
                            Description = "Ut vel impedit sit. Omnis quas et laboriosam possimus consectetur rerum.",
                            Status = "Internal",
                            Unit = 868m,
                            UnitPrice = 23415m,
                            UpdatedBy = "Jake",
                            UpdatedDate = new DateTime(2022, 4, 16, 15, 40, 56, 84, DateTimeKind.Local).AddTicks(4282)
                        },
                        new
                        {
                            Id = 317082575,
                            Category = "Computers",
                            CreatedBy = "Blanche",
                            CreatedDate = new DateTime(2021, 9, 15, 3, 20, 47, 725, DateTimeKind.Local).AddTicks(7870),
                            Description = "Voluptas enim ut esse voluptatem quae et rerum. Illum rerum et voluptas. Ducimus animi at totam est ad atque placeat quia unde.",
                            Status = "Kwacha",
                            Unit = 539m,
                            UnitPrice = 19553m,
                            UpdatedBy = "Blanche",
                            UpdatedDate = new DateTime(2021, 10, 31, 12, 38, 23, 25, DateTimeKind.Local).AddTicks(6739)
                        },
                        new
                        {
                            Id = 603711021,
                            Category = "Kids",
                            CreatedBy = "Sabrina",
                            CreatedDate = new DateTime(2022, 4, 29, 16, 28, 57, 619, DateTimeKind.Local).AddTicks(6893),
                            Description = "Quos pariatur quos iste ipsa blanditiis. Esse repellendus ut reprehenderit. Neque eum repudiandae perspiciatis.",
                            Status = "Toys, Grocery & Sports",
                            Unit = 299m,
                            UnitPrice = 21266m,
                            UpdatedBy = "Sabrina",
                            UpdatedDate = new DateTime(2021, 11, 25, 21, 23, 55, 401, DateTimeKind.Local).AddTicks(4907)
                        },
                        new
                        {
                            Id = 456567356,
                            Category = "Music",
                            CreatedBy = "Ron",
                            CreatedDate = new DateTime(2022, 5, 19, 18, 44, 37, 684, DateTimeKind.Local).AddTicks(2926),
                            Description = "Facere totam modi ipsa optio aut sed totam nihil quos. Voluptas esse eveniet voluptatem modi labore inventore est sit rerum.",
                            Status = "Berkshire",
                            Unit = 913m,
                            UnitPrice = 32285m,
                            UpdatedBy = "Ron",
                            UpdatedDate = new DateTime(2021, 9, 14, 17, 37, 18, 250, DateTimeKind.Local).AddTicks(1101)
                        },
                        new
                        {
                            Id = 624369253,
                            Category = "Books",
                            CreatedBy = "Johnny",
                            CreatedDate = new DateTime(2022, 2, 17, 19, 10, 12, 184, DateTimeKind.Local).AddTicks(7617),
                            Description = "Molestiae amet consequatur voluptatum quia et. Enim est aut quo. Neque temporibus libero sit omnis labore nobis explicabo aut voluptatem. Laborum sed sunt est dolorem voluptates.",
                            Status = "Practical Wooden Chair",
                            Unit = 880m,
                            UnitPrice = 10023m,
                            UpdatedBy = "Johnny",
                            UpdatedDate = new DateTime(2022, 2, 21, 11, 41, 16, 681, DateTimeKind.Local).AddTicks(6491)
                        },
                        new
                        {
                            Id = 505094876,
                            Category = "Home",
                            CreatedBy = "Kay",
                            CreatedDate = new DateTime(2021, 11, 22, 0, 14, 44, 843, DateTimeKind.Local).AddTicks(2257),
                            Description = "Aperiam reprehenderit id.",
                            Status = "maroon",
                            Unit = 24m,
                            UnitPrice = 3780m,
                            UpdatedBy = "Kay",
                            UpdatedDate = new DateTime(2021, 12, 30, 13, 5, 27, 482, DateTimeKind.Local).AddTicks(2061)
                        },
                        new
                        {
                            Id = 493975761,
                            Category = "Toys",
                            CreatedBy = "Cedric",
                            CreatedDate = new DateTime(2021, 8, 9, 0, 28, 2, 596, DateTimeKind.Local).AddTicks(1087),
                            Description = "Qui et optio nemo impedit optio perferendis. Dolorum vitae omnis doloremque vero accusamus quaerat consequuntur et tempora. Rerum enim aut at quae provident amet rerum dolores repudiandae. Ea ipsa rerum repellendus commodi expedita repudiandae fugiat illo nesciunt.",
                            Status = "Lempira",
                            Unit = 845m,
                            UnitPrice = 21069m,
                            UpdatedBy = "Cedric",
                            UpdatedDate = new DateTime(2021, 11, 19, 12, 35, 5, 17, DateTimeKind.Local).AddTicks(4422)
                        },
                        new
                        {
                            Id = 837133020,
                            Category = "Clothing",
                            CreatedBy = "Henrietta",
                            CreatedDate = new DateTime(2021, 11, 18, 18, 40, 3, 535, DateTimeKind.Local).AddTicks(8815),
                            Description = "Quod dolorem non. Aspernatur ad nam doloremque et harum illum sint rem.",
                            Status = "knowledge base",
                            Unit = 866m,
                            UnitPrice = 38676m,
                            UpdatedBy = "Henrietta",
                            UpdatedDate = new DateTime(2022, 3, 20, 9, 24, 43, 281, DateTimeKind.Local).AddTicks(9174)
                        },
                        new
                        {
                            Id = 867619000,
                            Category = "Baby",
                            CreatedBy = "Mandy",
                            CreatedDate = new DateTime(2021, 8, 5, 2, 27, 40, 346, DateTimeKind.Local).AddTicks(7760),
                            Description = "Dolorum quos culpa reiciendis consectetur id sit minima.",
                            Status = "Berkshire",
                            Unit = 40m,
                            UnitPrice = 14538m,
                            UpdatedBy = "Mandy",
                            UpdatedDate = new DateTime(2021, 8, 9, 17, 41, 2, 301, DateTimeKind.Local).AddTicks(3624)
                        },
                        new
                        {
                            Id = 447988766,
                            Category = "Health",
                            CreatedBy = "Beth",
                            CreatedDate = new DateTime(2022, 5, 8, 7, 48, 11, 895, DateTimeKind.Local).AddTicks(4806),
                            Description = "Et officiis voluptatem rem. Et velit nihil quaerat velit sunt doloribus non adipisci. Voluptatem et ratione voluptas vitae earum alias nemo.",
                            Status = "responsive",
                            Unit = 243m,
                            UnitPrice = 22609m,
                            UpdatedBy = "Beth",
                            UpdatedDate = new DateTime(2022, 2, 21, 17, 46, 22, 401, DateTimeKind.Local).AddTicks(5631)
                        },
                        new
                        {
                            Id = 358790566,
                            Category = "Sports",
                            CreatedBy = "Diane",
                            CreatedDate = new DateTime(2022, 5, 1, 12, 0, 4, 81, DateTimeKind.Local).AddTicks(7410),
                            Description = "Omnis commodi qui aperiam eaque quia aspernatur autem. Architecto quam pariatur libero quibusdam illo non est sequi commodi. Quas ut enim qui suscipit nam non occaecati adipisci. Eum nam eveniet voluptatem occaecati aut possimus.",
                            Status = "indexing",
                            Unit = 213m,
                            UnitPrice = 5716m,
                            UpdatedBy = "Diane",
                            UpdatedDate = new DateTime(2022, 1, 19, 7, 44, 17, 194, DateTimeKind.Local).AddTicks(2490)
                        },
                        new
                        {
                            Id = 258415954,
                            Category = "Garden",
                            CreatedBy = "Israel",
                            CreatedDate = new DateTime(2021, 10, 4, 13, 6, 53, 243, DateTimeKind.Local).AddTicks(5456),
                            Description = "Dolor voluptatum et qui perferendis. Facere eum sit consequatur molestias cupiditate aut suscipit odio ea. Facere doloremque laudantium voluptas nemo. Explicabo et at nemo sunt officia nihil et temporibus.",
                            Status = "Dynamic",
                            Unit = 368m,
                            UnitPrice = 42793m,
                            UpdatedBy = "Israel",
                            UpdatedDate = new DateTime(2022, 1, 2, 7, 35, 4, 999, DateTimeKind.Local).AddTicks(1580)
                        },
                        new
                        {
                            Id = 306806236,
                            Category = "Automotive",
                            CreatedBy = "Mike",
                            CreatedDate = new DateTime(2022, 5, 4, 20, 50, 28, 961, DateTimeKind.Local).AddTicks(4666),
                            Description = "Culpa ut magni. Cum in corporis delectus odio.",
                            Status = "Tools, Home & Books",
                            Unit = 970m,
                            UnitPrice = 48632m,
                            UpdatedBy = "Mike",
                            UpdatedDate = new DateTime(2022, 5, 4, 8, 39, 32, 739, DateTimeKind.Local).AddTicks(9818)
                        },
                        new
                        {
                            Id = 127821628,
                            Category = "Grocery",
                            CreatedBy = "Cristina",
                            CreatedDate = new DateTime(2021, 10, 26, 1, 38, 47, 918, DateTimeKind.Local).AddTicks(7363),
                            Description = "Sit voluptatibus facilis nostrum vero labore ea vel placeat. Facilis reprehenderit expedita a unde. Aspernatur ipsa quam.",
                            Status = "teal",
                            Unit = 719m,
                            UnitPrice = 24761m,
                            UpdatedBy = "Cristina",
                            UpdatedDate = new DateTime(2022, 1, 12, 16, 9, 2, 987, DateTimeKind.Local).AddTicks(493)
                        },
                        new
                        {
                            Id = 993942461,
                            Category = "Garden",
                            CreatedBy = "Frederick",
                            CreatedDate = new DateTime(2022, 6, 26, 10, 46, 58, 675, DateTimeKind.Local).AddTicks(7506),
                            Description = "Voluptatem quam autem repellat. Molestiae debitis consequatur odio nam corrupti illum voluptas provident voluptatem. Nihil est quam nemo deserunt ullam molestias rerum et. Est mollitia consequatur.",
                            Status = "Product",
                            Unit = 673m,
                            UnitPrice = 32625m,
                            UpdatedBy = "Frederick",
                            UpdatedDate = new DateTime(2022, 5, 21, 14, 1, 53, 100, DateTimeKind.Local).AddTicks(2642)
                        },
                        new
                        {
                            Id = 950548104,
                            Category = "Sports",
                            CreatedBy = "Rosa",
                            CreatedDate = new DateTime(2022, 5, 19, 9, 7, 44, 592, DateTimeKind.Local).AddTicks(5344),
                            Description = "Facere et consequuntur reiciendis quia nemo natus deserunt asperiores. Dolores ratione unde omnis temporibus. Iure velit necessitatibus sed ut nobis omnis. Assumenda reprehenderit dolorum qui dolores atque quo.",
                            Status = "Clothing",
                            Unit = 264m,
                            UnitPrice = 30733m,
                            UpdatedBy = "Rosa",
                            UpdatedDate = new DateTime(2022, 1, 17, 4, 58, 40, 155, DateTimeKind.Local).AddTicks(1279)
                        },
                        new
                        {
                            Id = 721347675,
                            Category = "Sports",
                            CreatedBy = "Vicki",
                            CreatedDate = new DateTime(2021, 11, 26, 22, 46, 35, 619, DateTimeKind.Local).AddTicks(6774),
                            Description = "Iure iure vel est cumque aut. Nisi maxime expedita. Doloribus eum ipsa officiis debitis consequatur et.",
                            Status = "pink",
                            Unit = 610m,
                            UnitPrice = 47622m,
                            UpdatedBy = "Vicki",
                            UpdatedDate = new DateTime(2022, 3, 8, 10, 18, 42, 72, DateTimeKind.Local).AddTicks(3410)
                        },
                        new
                        {
                            Id = 803284427,
                            Category = "Industrial",
                            CreatedBy = "Ian",
                            CreatedDate = new DateTime(2022, 3, 3, 10, 21, 37, 916, DateTimeKind.Local).AddTicks(5072),
                            Description = "Reiciendis incidunt numquam laudantium placeat aspernatur quia ut. Commodi porro unde qui aspernatur expedita repellat quia eum aspernatur.",
                            Status = "white",
                            Unit = 663m,
                            UnitPrice = 5537m,
                            UpdatedBy = "Ian",
                            UpdatedDate = new DateTime(2022, 6, 24, 12, 12, 23, 95, DateTimeKind.Local).AddTicks(2397)
                        },
                        new
                        {
                            Id = 790985800,
                            Category = "Tools",
                            CreatedBy = "Gregory",
                            CreatedDate = new DateTime(2022, 4, 25, 19, 19, 48, 869, DateTimeKind.Local).AddTicks(4914),
                            Description = "Adipisci et laudantium ab ut consectetur. Sit deleniti ab quam incidunt illo est ut. Omnis repellat vitae molestias cupiditate quibusdam quia unde.",
                            Status = "Bedfordshire",
                            Unit = 359m,
                            UnitPrice = 32982m,
                            UpdatedBy = "Gregory",
                            UpdatedDate = new DateTime(2021, 12, 22, 15, 54, 39, 77, DateTimeKind.Local).AddTicks(7766)
                        },
                        new
                        {
                            Id = 516059283,
                            Category = "Sports",
                            CreatedBy = "Jerald",
                            CreatedDate = new DateTime(2022, 6, 27, 3, 26, 9, 165, DateTimeKind.Local).AddTicks(3692),
                            Description = "Porro rem nisi est fuga expedita doloremque mollitia expedita veniam. Ipsum at nam quis eaque itaque odio.",
                            Status = "grey",
                            Unit = 782m,
                            UnitPrice = 2576m,
                            UpdatedBy = "Jerald",
                            UpdatedDate = new DateTime(2021, 11, 11, 15, 38, 55, 152, DateTimeKind.Local).AddTicks(9619)
                        },
                        new
                        {
                            Id = 265785763,
                            Category = "Grocery",
                            CreatedBy = "Gwen",
                            CreatedDate = new DateTime(2021, 10, 29, 8, 2, 8, 340, DateTimeKind.Local).AddTicks(7059),
                            Description = "Quia nihil possimus illum earum sed veniam et. Autem soluta fugiat enim perspiciatis dolorem. Eum molestiae ea sint voluptatem velit nobis rerum ipsum.",
                            Status = "driver",
                            Unit = 212m,
                            UnitPrice = 47730m,
                            UpdatedBy = "Gwen",
                            UpdatedDate = new DateTime(2022, 2, 20, 12, 17, 20, 933, DateTimeKind.Local).AddTicks(7160)
                        },
                        new
                        {
                            Id = 561776885,
                            Category = "Books",
                            CreatedBy = "Priscilla",
                            CreatedDate = new DateTime(2021, 11, 5, 22, 4, 54, 802, DateTimeKind.Local).AddTicks(4015),
                            Description = "Et nam quisquam rerum rerum.",
                            Status = "Barbados Dollar",
                            Unit = 317m,
                            UnitPrice = 38693m,
                            UpdatedBy = "Priscilla",
                            UpdatedDate = new DateTime(2022, 1, 4, 1, 15, 10, 761, DateTimeKind.Local).AddTicks(833)
                        },
                        new
                        {
                            Id = 517982222,
                            Category = "Games",
                            CreatedBy = "Barbara",
                            CreatedDate = new DateTime(2021, 12, 17, 12, 7, 52, 625, DateTimeKind.Local).AddTicks(2119),
                            Description = "Repellendus ratione voluptas dolor in. Velit autem omnis libero quae et aut. Dicta ea in velit est et modi ea.",
                            Status = "Ville",
                            Unit = 697m,
                            UnitPrice = 7829m,
                            UpdatedBy = "Barbara",
                            UpdatedDate = new DateTime(2021, 11, 15, 15, 54, 15, 97, DateTimeKind.Local).AddTicks(9084)
                        },
                        new
                        {
                            Id = 627732911,
                            Category = "Computers",
                            CreatedBy = "Derrick",
                            CreatedDate = new DateTime(2022, 7, 6, 20, 39, 41, 705, DateTimeKind.Local).AddTicks(9989),
                            Description = "Sint ab et. Labore qui dignissimos distinctio labore tempore ut consequatur provident tempore.",
                            Status = "methodologies",
                            Unit = 724m,
                            UnitPrice = 13402m,
                            UpdatedBy = "Derrick",
                            UpdatedDate = new DateTime(2022, 6, 27, 7, 30, 38, 72, DateTimeKind.Local).AddTicks(9642)
                        },
                        new
                        {
                            Id = 292425515,
                            Category = "Tools",
                            CreatedBy = "Mae",
                            CreatedDate = new DateTime(2022, 1, 9, 3, 0, 41, 62, DateTimeKind.Local).AddTicks(1021),
                            Description = "Vel soluta ex libero aliquid. Ratione iste veritatis impedit. Repudiandae atque esse deleniti adipisci.",
                            Status = "disintermediate",
                            Unit = 468m,
                            UnitPrice = 11255m,
                            UpdatedBy = "Mae",
                            UpdatedDate = new DateTime(2021, 9, 29, 1, 8, 29, 971, DateTimeKind.Local).AddTicks(3798)
                        },
                        new
                        {
                            Id = 159198385,
                            Category = "Tools",
                            CreatedBy = "Kyle",
                            CreatedDate = new DateTime(2021, 9, 3, 9, 25, 2, 655, DateTimeKind.Local).AddTicks(5468),
                            Description = "Et quod nisi. Voluptatem qui explicabo molestiae. Sint sed ad sed qui molestiae. Sint blanditiis omnis nesciunt mollitia placeat voluptate qui voluptatem accusantium.",
                            Status = "Fiji Dollar",
                            Unit = 904m,
                            UnitPrice = 27497m,
                            UpdatedBy = "Kyle",
                            UpdatedDate = new DateTime(2021, 8, 17, 9, 25, 23, 570, DateTimeKind.Local).AddTicks(1041)
                        },
                        new
                        {
                            Id = 519296789,
                            Category = "Garden",
                            CreatedBy = "Devin",
                            CreatedDate = new DateTime(2022, 1, 28, 1, 29, 49, 202, DateTimeKind.Local).AddTicks(4393),
                            Description = "Blanditiis vero qui et quibusdam natus ut repudiandae. Est voluptatum sint aut inventore odio sint molestias. Non laborum omnis fugiat impedit aliquid. Quas illo nemo ut recusandae doloremque ex est et.",
                            Status = "auxiliary",
                            Unit = 310m,
                            UnitPrice = 29936m,
                            UpdatedBy = "Devin",
                            UpdatedDate = new DateTime(2022, 3, 22, 19, 27, 45, 301, DateTimeKind.Local).AddTicks(6339)
                        },
                        new
                        {
                            Id = 807237170,
                            Category = "Jewelery",
                            CreatedBy = "Ricky",
                            CreatedDate = new DateTime(2022, 5, 12, 20, 0, 32, 557, DateTimeKind.Local).AddTicks(4939),
                            Description = "Sunt eveniet dolore suscipit autem laborum numquam laboriosam.",
                            Status = "Metrics",
                            Unit = 751m,
                            UnitPrice = 18214m,
                            UpdatedBy = "Ricky",
                            UpdatedDate = new DateTime(2022, 6, 2, 23, 29, 33, 411, DateTimeKind.Local).AddTicks(3368)
                        },
                        new
                        {
                            Id = 426630575,
                            Category = "Baby",
                            CreatedBy = "Christian",
                            CreatedDate = new DateTime(2022, 7, 15, 10, 36, 15, 5, DateTimeKind.Local).AddTicks(5158),
                            Description = "Nihil iure nobis ut aut. Omnis temporibus animi quis nam ea nesciunt nulla magni repellendus. Reiciendis necessitatibus repellat mollitia non.",
                            Status = "HTTP",
                            Unit = 503m,
                            UnitPrice = 40278m,
                            UpdatedBy = "Christian",
                            UpdatedDate = new DateTime(2021, 10, 13, 12, 16, 55, 135, DateTimeKind.Local).AddTicks(260)
                        },
                        new
                        {
                            Id = 599757923,
                            Category = "Movies",
                            CreatedBy = "Doreen",
                            CreatedDate = new DateTime(2021, 10, 23, 9, 7, 56, 539, DateTimeKind.Local).AddTicks(7807),
                            Description = "Et qui provident. In excepturi officia quisquam nostrum. Sed dolorem sunt totam magnam excepturi.",
                            Status = "Bermudian Dollar (customarily known as Bermuda Dollar)",
                            Unit = 77m,
                            UnitPrice = 7178m,
                            UpdatedBy = "Doreen",
                            UpdatedDate = new DateTime(2022, 1, 21, 14, 13, 41, 528, DateTimeKind.Local).AddTicks(8073)
                        },
                        new
                        {
                            Id = 923518155,
                            Category = "Automotive",
                            CreatedBy = "Sonya",
                            CreatedDate = new DateTime(2022, 7, 12, 20, 3, 34, 367, DateTimeKind.Local).AddTicks(3173),
                            Description = "Architecto dolor aut ut ut est odit. Debitis qui consectetur aut rem. Recusandae sunt reprehenderit nobis tenetur possimus quia aspernatur.",
                            Status = "Fort",
                            Unit = 33m,
                            UnitPrice = 42444m,
                            UpdatedBy = "Sonya",
                            UpdatedDate = new DateTime(2022, 2, 8, 16, 59, 23, 908, DateTimeKind.Local).AddTicks(4265)
                        },
                        new
                        {
                            Id = 136709641,
                            Category = "Grocery",
                            CreatedBy = "Gregg",
                            CreatedDate = new DateTime(2022, 6, 17, 8, 19, 35, 313, DateTimeKind.Local).AddTicks(3403),
                            Description = "Unde delectus sit culpa alias quis numquam molestias et. Deleniti explicabo debitis expedita soluta laudantium est quas.",
                            Status = "port",
                            Unit = 796m,
                            UnitPrice = 36588m,
                            UpdatedBy = "Gregg",
                            UpdatedDate = new DateTime(2022, 5, 10, 2, 20, 37, 235, DateTimeKind.Local).AddTicks(1332)
                        },
                        new
                        {
                            Id = 150262248,
                            Category = "Kids",
                            CreatedBy = "Terrence",
                            CreatedDate = new DateTime(2021, 9, 7, 1, 39, 33, 463, DateTimeKind.Local).AddTicks(5564),
                            Description = "Ut explicabo sint. Accusamus et reprehenderit minus vel et eveniet at. Occaecati maxime ut aut quasi. Inventore et rerum vel omnis.",
                            Status = "back up",
                            Unit = 259m,
                            UnitPrice = 42082m,
                            UpdatedBy = "Terrence",
                            UpdatedDate = new DateTime(2022, 5, 4, 20, 40, 46, 750, DateTimeKind.Local).AddTicks(8713)
                        },
                        new
                        {
                            Id = 769782974,
                            Category = "Sports",
                            CreatedBy = "Maxine",
                            CreatedDate = new DateTime(2022, 4, 3, 5, 47, 25, 50, DateTimeKind.Local).AddTicks(6912),
                            Description = "Est reiciendis eveniet dolor autem fugiat corporis itaque. Eius fugit odit ea eveniet vitae ea eveniet nostrum qui. Dolore natus officiis dolore enim quia ipsa voluptate.",
                            Status = "RSS",
                            Unit = 418m,
                            UnitPrice = 36947m,
                            UpdatedBy = "Maxine",
                            UpdatedDate = new DateTime(2022, 4, 8, 19, 30, 48, 615, DateTimeKind.Local).AddTicks(2534)
                        },
                        new
                        {
                            Id = 335928463,
                            Category = "Grocery",
                            CreatedBy = "Marcus",
                            CreatedDate = new DateTime(2022, 6, 3, 16, 16, 20, 958, DateTimeKind.Local).AddTicks(1575),
                            Description = "Ea quaerat omnis aut. Et sint et maiores distinctio quidem.",
                            Status = "Infrastructure",
                            Unit = 772m,
                            UnitPrice = 31263m,
                            UpdatedBy = "Marcus",
                            UpdatedDate = new DateTime(2022, 4, 18, 7, 16, 58, 376, DateTimeKind.Local).AddTicks(8179)
                        },
                        new
                        {
                            Id = 152170432,
                            Category = "Electronics",
                            CreatedBy = "Trevor",
                            CreatedDate = new DateTime(2022, 2, 3, 12, 35, 57, 586, DateTimeKind.Local).AddTicks(1063),
                            Description = "Qui a officiis qui eligendi repudiandae eligendi. Qui perferendis doloremque ea sit ratione autem.",
                            Status = "online",
                            Unit = 925m,
                            UnitPrice = 47773m,
                            UpdatedBy = "Trevor",
                            UpdatedDate = new DateTime(2021, 10, 25, 13, 52, 19, 84, DateTimeKind.Local).AddTicks(1939)
                        },
                        new
                        {
                            Id = 326790360,
                            Category = "Home",
                            CreatedBy = "Lori",
                            CreatedDate = new DateTime(2021, 8, 23, 15, 51, 45, 144, DateTimeKind.Local).AddTicks(7657),
                            Description = "Rerum delectus laborum dolores saepe quia. Aut velit repellat recusandae aut architecto sed expedita. Itaque quos nisi ut aut natus ratione sed sapiente quis.",
                            Status = "Solutions",
                            Unit = 457m,
                            UnitPrice = 12906m,
                            UpdatedBy = "Lori",
                            UpdatedDate = new DateTime(2022, 1, 10, 21, 11, 22, 309, DateTimeKind.Local).AddTicks(7720)
                        },
                        new
                        {
                            Id = 790602956,
                            Category = "Garden",
                            CreatedBy = "Russell",
                            CreatedDate = new DateTime(2022, 1, 18, 19, 23, 2, 565, DateTimeKind.Local).AddTicks(7128),
                            Description = "Magnam ea a culpa corporis soluta est. Eos distinctio eos aut et minima assumenda dolorum.",
                            Status = "back-end",
                            Unit = 211m,
                            UnitPrice = 5298m,
                            UpdatedBy = "Russell",
                            UpdatedDate = new DateTime(2021, 11, 8, 11, 29, 11, 219, DateTimeKind.Local).AddTicks(6591)
                        },
                        new
                        {
                            Id = 321987193,
                            Category = "Books",
                            CreatedBy = "Kevin",
                            CreatedDate = new DateTime(2021, 9, 13, 0, 8, 50, 433, DateTimeKind.Local).AddTicks(3515),
                            Description = "Incidunt est at dolorem voluptatem. Alias et veniam temporibus.",
                            Status = "Steel",
                            Unit = 656m,
                            UnitPrice = 14372m,
                            UpdatedBy = "Kevin",
                            UpdatedDate = new DateTime(2022, 4, 27, 1, 8, 16, 527, DateTimeKind.Local).AddTicks(3786)
                        },
                        new
                        {
                            Id = 707430730,
                            Category = "Baby",
                            CreatedBy = "Jesse",
                            CreatedDate = new DateTime(2022, 5, 14, 13, 42, 55, 22, DateTimeKind.Local).AddTicks(6250),
                            Description = "Quaerat et dicta aspernatur atque veritatis explicabo. Officiis vitae consequuntur dignissimos non voluptatibus et.",
                            Status = "compelling",
                            Unit = 829m,
                            UnitPrice = 1185m,
                            UpdatedBy = "Jesse",
                            UpdatedDate = new DateTime(2021, 7, 29, 14, 25, 55, 302, DateTimeKind.Local).AddTicks(6663)
                        },
                        new
                        {
                            Id = 922457951,
                            Category = "Automotive",
                            CreatedBy = "Robert",
                            CreatedDate = new DateTime(2022, 1, 23, 23, 29, 49, 847, DateTimeKind.Local).AddTicks(9338),
                            Description = "Voluptatem sapiente vel nihil omnis. Natus fugiat culpa unde qui voluptatem dolor. Ut est similique. Numquam voluptatem accusantium magni voluptas.",
                            Status = "infrastructures",
                            Unit = 104m,
                            UnitPrice = 23004m,
                            UpdatedBy = "Robert",
                            UpdatedDate = new DateTime(2022, 3, 6, 7, 15, 46, 980, DateTimeKind.Local).AddTicks(4942)
                        },
                        new
                        {
                            Id = 218530037,
                            Category = "Shoes",
                            CreatedBy = "Ronald",
                            CreatedDate = new DateTime(2022, 6, 25, 3, 37, 41, 137, DateTimeKind.Local).AddTicks(9652),
                            Description = "Architecto vero non tenetur placeat labore. Rerum culpa accusamus eum voluptate atque voluptatem. Expedita inventore dicta et sapiente quia odio aut.",
                            Status = "Legacy",
                            Unit = 290m,
                            UnitPrice = 26685m,
                            UpdatedBy = "Ronald",
                            UpdatedDate = new DateTime(2021, 9, 3, 17, 48, 52, 723, DateTimeKind.Local).AddTicks(131)
                        },
                        new
                        {
                            Id = 587192260,
                            Category = "Books",
                            CreatedBy = "Gilbert",
                            CreatedDate = new DateTime(2022, 1, 25, 8, 28, 4, 800, DateTimeKind.Local).AddTicks(8738),
                            Description = "Aliquid voluptatibus blanditiis debitis. Quibusdam voluptatum enim excepturi eius vitae autem numquam eum quo. Et modi temporibus dolores incidunt.",
                            Status = "program",
                            Unit = 404m,
                            UnitPrice = 31991m,
                            UpdatedBy = "Gilbert",
                            UpdatedDate = new DateTime(2022, 7, 14, 12, 30, 46, 768, DateTimeKind.Local).AddTicks(2157)
                        },
                        new
                        {
                            Id = 755702070,
                            Category = "Books",
                            CreatedBy = "Georgia",
                            CreatedDate = new DateTime(2022, 2, 1, 0, 45, 17, 15, DateTimeKind.Local).AddTicks(5864),
                            Description = "Asperiores quibusdam neque a ut ut ut. Error quibusdam doloremque autem. Soluta delectus doloremque.",
                            Status = "engineer",
                            Unit = 11m,
                            UnitPrice = 34030m,
                            UpdatedBy = "Georgia",
                            UpdatedDate = new DateTime(2022, 6, 6, 5, 42, 18, 985, DateTimeKind.Local).AddTicks(134)
                        },
                        new
                        {
                            Id = 791974913,
                            Category = "Industrial",
                            CreatedBy = "Sophie",
                            CreatedDate = new DateTime(2021, 7, 27, 9, 46, 49, 714, DateTimeKind.Local).AddTicks(5656),
                            Description = "Placeat quam enim ut ut autem eum est quia ut. Exercitationem at aut suscipit qui est ipsa. Velit quis ex. Cum voluptas non.",
                            Status = "efficient",
                            Unit = 360m,
                            UnitPrice = 48914m,
                            UpdatedBy = "Sophie",
                            UpdatedDate = new DateTime(2021, 8, 1, 10, 59, 37, 359, DateTimeKind.Local).AddTicks(8711)
                        },
                        new
                        {
                            Id = 489490870,
                            Category = "Automotive",
                            CreatedBy = "Grant",
                            CreatedDate = new DateTime(2021, 11, 27, 19, 4, 26, 816, DateTimeKind.Local).AddTicks(6313),
                            Description = "Dolore veritatis aut. Quas placeat itaque et voluptas molestiae ut. Aut qui numquam odio odio ipsam nulla harum soluta nemo.",
                            Status = "SCSI",
                            Unit = 57m,
                            UnitPrice = 7399m,
                            UpdatedBy = "Grant",
                            UpdatedDate = new DateTime(2021, 12, 1, 12, 0, 13, 344, DateTimeKind.Local).AddTicks(5274)
                        },
                        new
                        {
                            Id = 492279020,
                            Category = "Toys",
                            CreatedBy = "Roberto",
                            CreatedDate = new DateTime(2022, 6, 20, 14, 18, 33, 835, DateTimeKind.Local).AddTicks(6268),
                            Description = "Asperiores sint magni qui quaerat nisi repudiandae ut quisquam similique.",
                            Status = "Kroon",
                            Unit = 592m,
                            UnitPrice = 35441m,
                            UpdatedBy = "Roberto",
                            UpdatedDate = new DateTime(2021, 10, 20, 17, 14, 40, 630, DateTimeKind.Local).AddTicks(2739)
                        },
                        new
                        {
                            Id = 657694277,
                            Category = "Beauty",
                            CreatedBy = "Howard",
                            CreatedDate = new DateTime(2021, 11, 21, 11, 18, 59, 121, DateTimeKind.Local).AddTicks(5560),
                            Description = "Soluta qui expedita totam consectetur omnis voluptatibus.",
                            Status = "stable",
                            Unit = 233m,
                            UnitPrice = 14902m,
                            UpdatedBy = "Howard",
                            UpdatedDate = new DateTime(2021, 8, 18, 16, 11, 26, 498, DateTimeKind.Local).AddTicks(9235)
                        },
                        new
                        {
                            Id = 267755702,
                            Category = "Movies",
                            CreatedBy = "Elsie",
                            CreatedDate = new DateTime(2021, 7, 31, 10, 55, 4, 162, DateTimeKind.Local).AddTicks(6301),
                            Description = "Dolor maxime asperiores laudantium molestiae et consequatur. Eum perspiciatis voluptatibus ab aut sunt et ut labore fugiat. Illum sunt nemo est quo qui consectetur veniam explicabo inventore.",
                            Status = "Practical Cotton Keyboard",
                            Unit = 565m,
                            UnitPrice = 9232m,
                            UpdatedBy = "Elsie",
                            UpdatedDate = new DateTime(2022, 2, 22, 21, 24, 23, 592, DateTimeKind.Local).AddTicks(4813)
                        },
                        new
                        {
                            Id = 617230196,
                            Category = "Computers",
                            CreatedBy = "Bernard",
                            CreatedDate = new DateTime(2021, 10, 25, 18, 30, 26, 258, DateTimeKind.Local).AddTicks(941),
                            Description = "Consectetur aut praesentium sunt et unde nesciunt molestias.",
                            Status = "withdrawal",
                            Unit = 647m,
                            UnitPrice = 45508m,
                            UpdatedBy = "Bernard",
                            UpdatedDate = new DateTime(2021, 12, 5, 5, 11, 10, 498, DateTimeKind.Local).AddTicks(301)
                        },
                        new
                        {
                            Id = 683382139,
                            Category = "Movies",
                            CreatedBy = "Jeremiah",
                            CreatedDate = new DateTime(2021, 9, 3, 21, 27, 16, 938, DateTimeKind.Local).AddTicks(3488),
                            Description = "Repellat amet hic accusamus ipsa a fugiat et exercitationem sequi. Vel est qui reprehenderit totam placeat non non aut nihil. Soluta id maxime voluptas. Repellat alias placeat vel accusantium sapiente magni quos sint.",
                            Status = "homogeneous",
                            Unit = 787m,
                            UnitPrice = 49141m,
                            UpdatedBy = "Jeremiah",
                            UpdatedDate = new DateTime(2022, 4, 2, 0, 50, 55, 986, DateTimeKind.Local).AddTicks(9028)
                        },
                        new
                        {
                            Id = 406400086,
                            Category = "Books",
                            CreatedBy = "Don",
                            CreatedDate = new DateTime(2022, 4, 8, 8, 41, 12, 166, DateTimeKind.Local).AddTicks(9131),
                            Description = "Harum magni asperiores dolorem id. Corrupti a fugit atque.",
                            Status = "withdrawal",
                            Unit = 142m,
                            UnitPrice = 48217m,
                            UpdatedBy = "Don",
                            UpdatedDate = new DateTime(2021, 8, 9, 5, 38, 48, 613, DateTimeKind.Local).AddTicks(4928)
                        },
                        new
                        {
                            Id = 192528617,
                            Category = "Electronics",
                            CreatedBy = "Velma",
                            CreatedDate = new DateTime(2022, 3, 2, 23, 54, 56, 541, DateTimeKind.Local).AddTicks(7193),
                            Description = "Atque minima dolores velit accusantium exercitationem rem.",
                            Status = "Central",
                            Unit = 779m,
                            UnitPrice = 37499m,
                            UpdatedBy = "Velma",
                            UpdatedDate = new DateTime(2021, 11, 19, 15, 20, 41, 407, DateTimeKind.Local).AddTicks(2398)
                        },
                        new
                        {
                            Id = 670276711,
                            Category = "Jewelery",
                            CreatedBy = "Ruben",
                            CreatedDate = new DateTime(2022, 5, 18, 8, 41, 41, 589, DateTimeKind.Local).AddTicks(1243),
                            Description = "Est quis dolores quaerat et earum. Incidunt eaque reprehenderit iure natus. Nemo maxime et. Qui sapiente fugit velit eum nemo dolorem accusantium.",
                            Status = "vortals",
                            Unit = 561m,
                            UnitPrice = 21139m,
                            UpdatedBy = "Ruben",
                            UpdatedDate = new DateTime(2021, 8, 8, 17, 1, 51, 901, DateTimeKind.Local).AddTicks(612)
                        },
                        new
                        {
                            Id = 652338878,
                            Category = "Outdoors",
                            CreatedBy = "Alison",
                            CreatedDate = new DateTime(2021, 9, 12, 10, 22, 42, 376, DateTimeKind.Local).AddTicks(7051),
                            Description = "Non iusto sed impedit sed voluptates ut odio at molestiae. Molestiae consectetur non suscipit ea repellendus quo dolorem enim ratione. Provident harum nesciunt iure asperiores a qui. Odit facere ea omnis qui quam in.",
                            Status = "methodologies",
                            Unit = 804m,
                            UnitPrice = 45398m,
                            UpdatedBy = "Alison",
                            UpdatedDate = new DateTime(2022, 6, 5, 9, 38, 22, 902, DateTimeKind.Local).AddTicks(678)
                        },
                        new
                        {
                            Id = 913042727,
                            Category = "Shoes",
                            CreatedBy = "Lynn",
                            CreatedDate = new DateTime(2021, 10, 3, 13, 2, 37, 668, DateTimeKind.Local).AddTicks(9615),
                            Description = "Aut sed voluptatem tempore non nam iste et mollitia. Quos libero voluptatem natus quae. Numquam quaerat reprehenderit iste nulla iste libero soluta sequi voluptatem. Incidunt est et ut.",
                            Status = "array",
                            Unit = 769m,
                            UnitPrice = 18961m,
                            UpdatedBy = "Lynn",
                            UpdatedDate = new DateTime(2022, 5, 23, 12, 43, 35, 332, DateTimeKind.Local).AddTicks(1704)
                        },
                        new
                        {
                            Id = 793808743,
                            Category = "Tools",
                            CreatedBy = "Darrin",
                            CreatedDate = new DateTime(2022, 4, 11, 8, 0, 45, 477, DateTimeKind.Local).AddTicks(9751),
                            Description = "Asperiores similique fuga consectetur veritatis et qui illum dicta. Vel voluptatem dolorum libero aliquid nihil qui et. Et ipsa dicta dicta.",
                            Status = "open-source",
                            Unit = 271m,
                            UnitPrice = 28324m,
                            UpdatedBy = "Darrin",
                            UpdatedDate = new DateTime(2021, 11, 22, 21, 46, 26, 532, DateTimeKind.Local).AddTicks(5420)
                        },
                        new
                        {
                            Id = 579325015,
                            Category = "Tools",
                            CreatedBy = "Milton",
                            CreatedDate = new DateTime(2022, 6, 6, 18, 6, 12, 60, DateTimeKind.Local).AddTicks(5336),
                            Description = "Iusto ut animi porro maxime ut rem alias velit. Ut beatae voluptatem inventore quam exercitationem dicta reprehenderit eos.",
                            Status = "Rapid",
                            Unit = 402m,
                            UnitPrice = 36850m,
                            UpdatedBy = "Milton",
                            UpdatedDate = new DateTime(2021, 11, 11, 17, 45, 42, 496, DateTimeKind.Local).AddTicks(4510)
                        },
                        new
                        {
                            Id = 828758638,
                            Category = "Sports",
                            CreatedBy = "Kristin",
                            CreatedDate = new DateTime(2022, 4, 5, 11, 29, 54, 667, DateTimeKind.Local).AddTicks(1768),
                            Description = "Aliquid velit officiis. Quod possimus ut totam ut sapiente. Et nostrum ut qui eum atque nihil blanditiis magnam vitae.",
                            Status = "Research",
                            Unit = 694m,
                            UnitPrice = 16996m,
                            UpdatedBy = "Kristin",
                            UpdatedDate = new DateTime(2022, 7, 23, 19, 55, 1, 692, DateTimeKind.Local).AddTicks(4118)
                        });
                });

            modelBuilder.Entity("Mobiliva.DataAccess.Data.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("Mobiliva.DataAccess.Data.OrderDetail", b =>
                {
                    b.HasOne("Mobiliva.DataAccess.Data.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mobiliva.DataAccess.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
